baseURL = "https://yeqiongzhou.top" # <head> 里面的 baseurl 信息，填你的博客地址
languageCode = "zh-cn" # 语言
title = "叶琼州的代码小窝" # 浏览器的标题
hasCJKLanguage = true # 开启可以让「字数统计」统计汉字
theme = "LeaveIt" # 主题 (需要自己下载)

paginate = 11 # 每页的文章数
enableEmoji = true # 支持 Emoji
enableRobotsTXT = true # 支持 robots.txt
googleAnalytics = "UA-135209530-1" # Google 统计 id

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
  posts = "/:year/:month/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4


[params]
    since = 2019
    author = "叶琼州"                          # Author's name
    avatar = "/images/me/avatar.png"           # Author's avatar
    subtitle = "Talk is cheap. Show me the code." # Subtitle
    cdn_url = "img.yeqiongzhou.top.qiniudns.com"           # Base CDN URL
    home_mode = "" # post or other
    enableGitalk = true # gitalk 评论系统
    google_verification = ""
    description = "叶琼州的个人博客" # (Meta) 描述
    keywords = "blog, hugo, go, docker, kubernetes, k8s, bodhiye, yeqiongzhou, 叶琼州" # site keywords
    beian = "赣ICP备17015897号-2"
    baiduAnalytics = "5a98ee17bdb34762db31e4198f3a26ac"
    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "bodhiye"
    LinkedIn = "yeqiongzhou"
    Email   = "yeqiongzhou@whu.edu.cn"
    Wechat = "/images/me/wechat.jpeg"  # Wechat QRcode image
    Twitter = "yeqiongzhou"
    Instagram = "yeqiongzhou"
    Facebook = "yeqiongzhou"
    # Telegram = "xxoo"
    # Dribbble = "xxoo"
    # Medium = "xxoo"

[params.gitalk] # Github: https://github.com/gitalk/gitalk
    clientID = "abe0462addf2bb7816db" # Your client ID
    clientSecret = "302211bbfc34be3c75ec4cfa8751002e796356fa" # Your client secret
    repo = "bodhiye.github.io" # The repo to store comments
    owner = "bodhiye" # Your GitHub ID
    admin= "bodhiye" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id= "location.pathname" # The unique id of the page.
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= false # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode= true # Enable hot key (cmd|ctrl + enter) submit comment.
