name: Deploy Hugo Site to Github Pages on Master Branch

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - master

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v1
        with:
          persist-credentials: false

      # 安装 Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.62.2'
          extended: true

      - name: Build
        run: hugo --gc --minify --cleanDestinationDir

      # 部署到 GitHub Pages
      - name: Deploy
        uses: peaceiris/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          keep_files: false
          commit_message: ${{ github.event.head_commit.message }}
